sudo: false
dist: xenial
cache:
  directories:
    - $HOME/.cache/pip
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -U pip
  - "pip install -e .[dev,convert]"
script:
  - flake8 openssh_key
  - py.test -vvv --cov openssh_key
after_success:
  - bash <(curl -s https://codecov.io/bash)
